import type { CaseData } from "@/components/useInvestigation";

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function slug(s: string): string {
  return s.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").toLowerCase().slice(0, 40);
}

/** Professional Markdown report preserving evidence, sources and confidence. */
export function exportMarkdown(data: CaseData) {
  const r = data.report;
  if (!r) return;
  const q = data.identifier?.raw ?? "investigation";
  const L: string[] = [];
  L.push(`# Investigation Report — ${q}`);
  L.push("");
  L.push(`_Generated by Graphline · ${new Date().toISOString().slice(0, 16).replace("T", " ")} UTC_`);
  L.push(`_Risk level: **${r.riskLevel}** · Analysis: ${r.aiGenerated ? "AI investigator" : "deterministic"}_`);
  L.push("");
  L.push("## Executive summary");
  L.push(r.executiveSummary);
  L.push("");
  L.push("## Most likely identity");
  L.push(`**${r.mostLikelyIdentity}** — confidence ${Math.round(r.identityConfidence * 100)}%`);
  L.push("");
  L.push("## Public exposure");
  L.push(`**${r.exposureScore}/100 — ${r.exposureBand}**`);
  r.exposureFactors.forEach((f) => L.push(`- ${f.label} — ${f.detail}`));
  L.push("");
  L.push("## Digital footprint");
  r.digitalFootprint.forEach((f) => L.push(`- ${f}`));
  L.push("");
  if (r.associatedUsernames.length) {
    L.push("## Associated usernames");
    L.push(r.associatedUsernames.map((u) => `\`${u}\``).join(", "));
    L.push("");
  }
  if (r.associatedWebsites.length) {
    L.push("## Associated websites");
    r.associatedWebsites.forEach((w) => L.push(`- ${w}`));
    L.push("");
  }
  if (r.possibleOrganizations.length) {
    L.push("## Possible organizations");
    r.possibleOrganizations.forEach((o) => L.push(`- ${o}`));
    L.push("");
  }
  if (r.knownAccounts.length) {
    L.push("## Known accounts");
    r.knownAccounts.forEach((a) => L.push(`- ${a.platform}: ${a.url}`));
    L.push("");
  }
  if (r.scamIndicators.length) {
    L.push("## Risk & scam indicators");
    r.scamIndicators.forEach((s) => L.push(`- ⚠ ${s}`));
    L.push("");
  }
  L.push("## Supporting evidence");
  r.supportingEvidence.forEach((s) => L.push(`- ${s}`));
  L.push("");
  L.push("## Conflicting / uncertain");
  r.conflictingEvidence.forEach((s) => L.push(`- ${s}`));
  L.push("");
  L.push("## Confidence");
  L.push(r.confidenceExplanation);
  L.push("");
  L.push("## Recommended verification steps");
  r.nextSteps.forEach((s, i) => L.push(`${i + 1}. ${s}`));
  L.push("");
  if (data.timeline.length) {
    L.push("## Timeline");
    [...data.timeline]
      .sort((a, b) => a.at.localeCompare(b.at))
      .forEach((t) => L.push(`- **${t.at.slice(0, 10)}** — ${t.label}${t.detail ? `: ${t.detail}` : ""}`));
    L.push("");
  }
  L.push("## Evidence ledger");
  data.evidence
    .filter((e) => e.sourceId !== "seed")
    .sort((a, b) => b.weight - a.weight)
    .forEach((e) => {
      L.push(`- **[${e.sourceLabel}]** ${e.title} — ${e.detail}${e.url ? ` (${e.url})` : ""}`);
    });
  L.push("");
  L.push("---");
  L.push("_Graphline uses only publicly available information. Findings are leads to verify, not verdicts._");

  download(`graphline-${slug(q)}.md`, L.join("\n"), "text/markdown");
}

export function exportJSON(data: CaseData) {
  const q = data.identifier?.raw ?? "investigation";
  const payload = {
    query: q,
    identifier: data.identifier,
    generatedAt: new Date().toISOString(),
    report: data.report,
    entities: data.entities,
    relationships: data.relationships,
    evidence: data.evidence,
    timeline: data.timeline,
  };
  download(`graphline-${slug(q)}.json`, JSON.stringify(payload, null, 2), "application/json");
}
